---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fancyweb-server
  labels: 
    run: fancyweb-server
spec:
  selector:
    matchLabels:
      run: fancyweb-server
  replicas: 1
  template:
    metadata:
      labels:
        run: fancyweb-server
    spec:
      containers:
      - name: fancyweb-server
        image: ronaksh/fancyweb:latest
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
kind: Service
apiVersion: v1
metadata:
  name: fancyweb-server
  labels:
    run: fancyweb-server
spec:
  type: NodePort
  selector:
    run: fancyweb-server
  ports:
  # Default port used by the image
  - name: web
    port: 9091
    targetPort: 9091
    nodePort: 30000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2021-09-04T19:52:25Z"
  name: fancyweb-operator
  namespace: default
  resourceVersion: "1580"
  uid: 8e70671a-47ff-4cdd-8f9c-30539700dfbd
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fancyweb-server
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 1
  desiredReplicas: 0

