apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2021-09-04T19:52:25Z"
  name: operator
  namespace: default
  resourceVersion: "1580"
  uid: 8e70671a-47ff-4cdd-8f9c-30539700dfbd
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Pod
    name: baeldung-app
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 1
  desiredReplicas: 0
